kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus
  annotations:
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  volumeMode: Filesystem